### ISSUE TITLE
Supporting jvm and other platforms?

### ISSUE THREAD

**Issue by glureau** [TM-Apps/konnection#3]
Using this library in some low-level libraries, I find it hard to add new platforms.

I know it makes no sense most of the time to check connectivity on a jvm project (assuming backend), but sometimes I think it does(jvm desktop for example). Also even a default implementation that consider the device always connected would be a cool shortcut for me.

What do you think?

**Comment by magnumrocha** [comment]
Hi @glureau , just released the version 1.2.0 with the JVM target
