### ISSUE TITLE
[Android] Does not recognise BT-Tethering

### ISSUE THREAD

**Issue by boldtrn** [TM-Apps/konnection#5]
Thanks for providing this neat library. We have found an issue when using the library though, it does not recognise connections via BT tethering on Android. SIM and WiFi work fine.

**Comment by magnumrocha** [comment]
Hi @boldtrn, since version [1.4.0](https://github.com/TM-Apps/konnection/releases/tag/1.4.0), the library recognizes Bluetooth Tethering and Ethernet connection.

**Comment by boldtrn** [comment]
Awesome, thanks for the update 👍
