### ISSUE TITLE
remove android:maxSdkVersion

### ISSUE THREAD

**Issue by b95505017** [TM-Apps/konnection#6]
https://developer.android.com/guide/topics/manifest/uses-sdk-element

Currently the generated `AndroidManifest.xml` will declared `android:maxSdkVersion="34"`, which will block android version > 34 to install app which use this library. Official guidance also don't recommend library declared this attribute.

**Comment by magnumrocha** [comment]
Hi, thanks for the feedback.

This is an Issue with Amper:
https://youtrack.jetbrains.com/issue/AMPER-813

So, I'll track this Issue and as soon it is fixed I will generate a new version of the library.

Please vote for the Issue on Youtrack 🙏

**Comment by magnumrocha** [comment]
Hi, this Issue was fixed in version [1.4.2](https://github.com/TM-Apps/konnection/releases/tag/1.4.2).
