### ISSUE TITLE
Is bluetooth permission necessary? 

### ISSUE THREAD

**Issue by b95505017** [TM-Apps/konnection#7]
https://github.com/TM-Apps/konnection/blob/master/konnection/src%40android/AndroidManifest.xml#L6

I couldn't find any api usage require bluetooth permission.

**Comment by magnumrocha** [comment]
It will be removed in the next version.

**Comment by magnumrocha** [comment]
Hi, the permission was removed in version [1.4.2](https://github.com/TM-Apps/konnection/releases/tag/1.4.2).
