### ISSUE TITLE
Bugs konnection not update type connection

### ISSUE THREAD

**Issue by hafiz013** [TM-Apps/konnection#8]
When I try open wifi first time it given correct wifi type.But, when i try off wifi and try to get back this function still return wifi type.

Below here my sample code:

```
class ConnectionNetworkChecker : NetworkChecker {
    private val konnection = Konnection.createInstance(true)

    override  fun isInternetAvailable(): Boolean {
        return when(konnection.getCurrentNetworkConnection()){
            NetworkConnection.WIFI, NetworkConnection.MOBILE, NetworkConnection.ETHERNET -> true
            else-> false
        }
    }
}
```

```
interface NetworkChecker {
    fun isInternetAvailable(): Boolean
}
```

Note: I do this in kotlin multiplatform. Both ios and android not showing correct result type connection.

**Comment by hafiz013** [comment]
@magnumrocha any update on my issue?

**Comment by magnumrocha** [comment]
@hafiz013 thank you for your feedback.

I've just tested the scenario you described, and the Konnection library works fine.

Check the attached video. 
https://github.com/user-attachments/assets/bbd1696c-db37-45c0-a657-313c0548cac9


Can you share more details about your Issue?

**Comment by magnumrocha** [comment]
Closing this Issue due the lack of feedback.
