### ISSUE TITLE
Incorrect  value connection for JWM. 

### ISSUE THREAD

**Issue by Anika1d** [TM-Apps/konnection#9]
![image](https://github.com/user-attachments/assets/3928f658-bbf9-420e-8588-a5553b17dfa4)
since the name of my equipment does not contain hardcoded parts, then when checking the internet connection, it always returns false

**Comment by Anika1d** [comment]
https://github.com/TM-Apps/konnection/pull/10

**Comment by magnumrocha** [comment]
Hi @Anika1d , thanks for your comment and PR.

On version [1.4.2](https://github.com/TM-Apps/konnection/releases/tag/1.4.2), I've introduced a fix for this case:

Now, the Konnection constructor for JVM target accepts new parameters:
```kotlin
val konnection = Konnection.createInstance(
    connectionCheckTime = 5.seconds,
    pingHostCheckers = listOf("myhost.com"),
    wifiNetworkInterfaces = listOf("wi-fi", "wireless", "wlan0"),
    ethernetNetworkInterfaces = listOf("ethernet", "lan", "eth0", "eth1")
    ...
)
```
As you can see, you can specify your Network Interface names for Wi-Fi and Ethernet cases.
This solution makes the library more flexible and future-proof.

You can check on code the default values for these properties: [Konnection.jvm.kt](https://github.com/TM-Apps/konnection/blob/master/konnection/src%40jvm/Konnection.jvm.kt)
